const guideTTEnergies = [
  {
    name: "1 код долі “Енергія Мага”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "1 код долі <span>“Енергія Мага”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "2 код долі “Енергія Верховної Жриці”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "2 код долі <span>“Енергія Верховної Жриці”</span> ",
    price: "33€",
    link: "#",
  },
  {
    name: "3 код долі “Енергія Імператриці” в житті жінки",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "3 код долі <span>“Енергія Імператриці” в житті жінки</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "3 код долі “Енергія Імператриці” в житті чоловіка",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "3 код долі <span>“Енергія Імператриці” в житті чоловіка</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "4 код долі “Енергія Імператора” в житті жінки",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "4 код долі <span>“Енергія Імператора” в житті жінки</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "4 код долі “Енергія Імператора” в житті чоловіка",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "4 код долі <span>“Енергія Імператора” в житті чоловіка</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "5 код долі “Енергія Вчителя, Учня, Ієрофанта”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "5 код долі <span>“Енергія Вчителя, Учня, Ієрофанта”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "6 код долі “Енергія Кохання та Відносин”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "6 код долі <span>“Енергія Кохання та Відносин”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "7 код долі “Енергія Воїна”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "7 код долі <span>“Енергія Воїна”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "8 код долі “Енергія Кармічної Справдливості”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "8 код долі <span>“Енергія Кармічної Справедливості”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "9 код долі “Енергія Мудреця, Відлюдника”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "9 код долі <span>“Енергія Мудреця, Відлюдника”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "10 код долі “Енергія Фортуни”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "1 код долі <span>“Енергія Фортуни”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "11 код долі “Енергія Сили та Потенціалу”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "11 код долі <span>“Енергія Сили та Потенціалу”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "12 код долі “Енергія Служіння Людям”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "12 код долі <span>“Енергія Служіння Людям”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "13 код долі “Енергія Смерті та Трансформації”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "13 код долі <span>“Енергія Смерті Та Трансформації”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "14 код долі “Енергія Зрілої Душі”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "14 код долі <span>“Енергія Зрілої Душі”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "15 код долі “Енергія Темного Ангела”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "15 код долі <span>“Енергія Темного Ангела”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "16 код долі “Енергія Духовного Пробудження”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "16 код долі <span>“Енергія Духовного Пробудження”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "17 код долі “Енергія Зірки”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "17 код долі <span>“Енергія Зірки”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "18 код долі “Енергія Місяця і Страхів”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "18 код долі <span>“Енергія Місяця і Страхів”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "19 код долі “Енергія Сонця”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "19 код долі <span>“Енергія Сонця”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "20 код долі “Енергія Роду”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "20 код долі <span>“Енергія Роду”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "21 код долі “Енергія Миру”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "21 код долі <span>“Енергія Миру”</span>",
    price: "33€",
    link: "#",
  },
  {
    name: "22 код долі “Енергія Вищої Духовної Свободи”",
    isWaiting: false,
    category: "guideAndBooks",
    cardName: "1 код долі <span>“Енергія Вищої Духовної Свободи”</span>",
    price: "33€",
    link: "#",
  },
];

const otherGuidesList = [
  {
    name: "Солярний гайд",
    img: "/assets/images/meditations/other_guides.webp",
    price: "144€",
    link: "#",
  },
];

const booksList = [
  {
    name: "Книга “Технології тренінгу: улюблений  “складний” учасник”",
    img: "/assets/images/meditations/book1.webp",
    price: "7€",
    link: "#",
  },
  {
    name: "Книга “Тренінгові вправи для початківців та професіоналів”",
    img: "/assets/images/meditations/book2.webp",
    price: "7€",
    link: "#",
  },
];

const list = { guideTTEnergies, otherGuidesList, booksList };

export default list;
