export const gifts = [
  { name: { uk: 'PUBLISHED1' }, status: 'PUBLISHED', id: '1' },
  { name: { uk: 'draft1' }, status: 'DRAFT', id: '2' },
  { name: { uk: 'hidden4' }, status: 'HIDDEN', id: '3' },
  { name: { uk: 'PUBLISHED2' }, status: 'PUBLISHED', id: '4' },
  { name: { uk: 'DRAFT2' }, status: 'DRAFT', id: '5' },
  { name: { uk: 'HIDDEN3' }, status: 'HIDDEN', id: '6' },
  { name: { uk: 'PUBLISHED3' }, status: 'PUBLISHED', id: '7' },
  { name: { uk: 'DRAFT3' }, status: 'DRAFT', id: '8' },
  { name: { uk: 'HIDDEN132' }, status: 'HIDDEN', id: '9' },
  { name: { uk: 'PUBLISHED4' }, status: 'PUBLISHED', id: '10' },
  { name: { uk: 'DRAFT4' }, status: 'DRAFT', id: '11' },
  { name: { uk: 'HIDDEN546' }, status: 'HIDDEN', id: '12' },
  { name: { uk: 'Укрмова' }, status: 'HIDDEN', id: '13' },
];
