export const guide_and_books = [
  { name: { uk: 'PUBLISHED1' }, status: 'PUBLISHED', id: '21', category: 'GUIDES' },
  { name: { uk: 'draft1' }, status: 'DRAFT', id: '22', category: 'BOOKS' },
  { name: { uk: 'hidden4' }, status: 'HIDDEN', id: '23', category: 'GUIDES' },
  { name: { uk: 'PUBLISHED2' }, status: 'PUBLISHED', id: '24', category: 'BOOKS' },
  { name: { uk: 'DRAFT2' }, status: 'DRAFT', id: '25', category: 'GUIDES' },
  { name: { uk: 'HIDDEN3' }, status: 'HIDDEN', id: '26', category: 'BOOKS' },
  { name: { uk: 'PUBLISHED3' }, status: 'PUBLISHED', id: '27', category: 'GUIDES' },
  { name: { uk: 'DRAFT3' }, status: 'DRAFT', id: '28', category: 'BOOKS' },
  { name: { uk: 'HIDDEN132' }, status: 'HIDDEN', id: '29', category: 'OTHER_GUIDES' },
  { name: { uk: 'PUBLISHED4' }, status: 'PUBLISHED', id: '210', category: 'OTHER_GUIDES' },
  { name: { uk: 'DRAFT4' }, status: 'DRAFT', id: '211', category: 'OTHER_GUIDES' },
  { name: { uk: 'HIDDEN546' }, status: 'HIDDEN', id: '212', category: 'OTHER_GUIDES' },
  { name: { uk: 'Укрмова' }, status: 'HIDDEN', id: '213', category: 'OTHER_GUIDES' },
];
