export const meditations = [
  { name: 'published1', status: 'published', id: '1', category: 'opened' },
  { name: 'draft1', status: 'draft', id: '2', category: 'arcanes' },
  { name: 'hidden4', status: 'hidden', id: '3', category: 'opened' },
  { name: 'published2', status: 'published', id: '4', category: 'arcanes' },
  { name: 'draft2', status: 'draft', id: '5', category: 'closed' },
  { name: 'hidden3', status: 'hidden', id: '6', category: 'arcanes' },
  { name: 'published3', status: 'published', id: '7', category: 'closed' },
  { name: 'draft3', status: 'draft', id: '8', category: 'arcanes' },
  { name: 'hidden132', status: 'hidden', id: '9', category: 'closed' },
  { name: 'published4', status: 'published', id: '10', category: 'closed' },
  { name: 'draft4', status: 'draft', id: '11', category: 'closed' },
  { name: 'hidden546', status: 'hidden', id: '12', category: 'closed' },
  { name: 'Укрмова', status: 'hidden', id: '13', category: 'closed' },
];
