export const users = [
  {
    name: 'Art',
    lastName: 'Gry',
    mobPhone: '+380991231231',
    email: 'test@gmail.com',
    product: 'Курс навчання',
    createdAt: Date.now(),
    lastLogin: Date.now(),
    blocked: true,
    id: 1,
  },
  {
    name: 'Art',
    lastName: 'Gry',
    mobPhone: '+380991231231',
    product: 'Курс навчання',
    email: 'test@gmail.com',
    createdAt: Date.now(),
    lastLogin: Date.now(),
    blocked: true,
    id: 2,
  },
  {
    name: 'Prt',
    lastName: 'Dryqweqwdas',
    mobPhone: '+380991231231',
    product: 'Курс навчання',
    createdAt: Date.now(),
    email: 'test@gmail.com',
    lastLogin: Date.now(),
    blocked: false,
    id: 3,
  },
];
