export const webinarsList = [
  { name: { uk: 'PUBLISHED1' }, status: 'PUBLISHED', id: '1', category: 'WEBINARS' },
  { name: { uk: 'draft1' }, status: 'DRAFT', id: '2', category: 'ETHERS' },
  { name: { uk: 'hidden4' }, status: 'HIDDEN', id: '3', category: 'WEBINARS' },
  { name: { uk: 'PUBLISHED2' }, status: 'PUBLISHED', id: '4', category: 'ETHERS' },
  { name: { uk: 'DRAFT2' }, status: 'DRAFT', id: '5', category: 'WEBINARS' },
  { name: { uk: 'HIDDEN3' }, status: 'HIDDEN', id: '6', category: 'ETHERS' },
  { name: { uk: 'PUBLISHED3' }, status: 'PUBLISHED', id: '7', category: 'WEBINARS' },
  { name: { uk: 'DRAFT3' }, status: 'DRAFT', id: '8', category: 'ETHERS' },
  { name: { uk: 'HIDDEN132' }, status: 'HIDDEN', id: '9', category: 'WEBINARS' },
  { name: { uk: 'PUBLISHED4' }, status: 'PUBLISHED', id: '10', category: 'WEBINARS' },
  { name: { uk: 'DRAFT4' }, status: 'DRAFT', id: '11', category: 'WEBINARS' },
  { name: { uk: 'HIDDEN546' }, status: 'HIDDEN', id: '12', category: 'WEBINARS' },
  { name: { uk: 'Укрмова' }, status: 'HIDDEN', id: '13', category: 'WEBINARS' },
];
